### ISSUE TITLE
Rewrite `EqSat.Internal.MHashMap` to use Judy arrays

### ISSUE THREAD

**Issue by taktoa** [taktoa/eqsat#3]
I suspect there could be a performance improvement if we used [Judy arrays](https://hackage.haskell.org/package/judy) for `EqSat.Internal.MHashMap`. We'd probably need to make our own typeclass that replaces `Hashable` with something that will work better with the performance characteristics of Judy arrays (since sparse keys are undesirable).

- [ ] Figure out whether or not it is safe to use the functions from `judy` with `unsafeIOToST`.
- [ ] Write a wrapper module over `Data.Judy` that exposes a cleaner interface using `ST`.
- [ ] Write benchmarks for `EqSat.Internal.MHashMap`.
- [ ] Write a typeclass for hashing into keys usable in Judy arrays.
- [ ] Switch `EqSat.Internal.MHashMap` over to Judy arrays.

**Comment by chessai** [comment]
the checkboxes
